name: XCFramework
on:
  push:
    branches:
    - main

jobs:
  create_release:
    name: Build Framework
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@main
      - name: Create XCFramework
        run: |
          xcodebuild archive -scheme Test_Framework -destination="iOS" -archivePath /tmp/xcf/ios.xcarchive -derivedDataPath /tmp/iphoneos -sdk iphoneos SKIP_INSTALL=NO && xcodebuild archive -scheme Test_Framework -destination="iOS Simulator" -archivePath /tmp/xcf/iossimulator.xcarchive -derivedDataPath /tmp/iphoneos -sdk iphonesimulator SKIP_INSTALL=NO && xcodebuild -create-xcframework -framework /tmp/xcf/ios.xcarchive/Products/Library/Frameworks/Test_Framework.framework -framework /tmp/xcf/iossimulator.xcarchive/Products/Library/Frameworks/Test_Framework.framework -output Test_Framework.xcframework && cd /Users/runner/work/Test_Framework/Test_Framework && ls && git remote remove origin && git remote add origin https://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@github.com/suhas03su/Test_Framework && git add . && git commit -m "pushing from github actions" && git push origin HEAD:3.0

      # Create a release
      # Upload those artifacts to the release
