name: Cocopods
on:
  push:
    branches:
    - main

jobs:
  job1:
    name: Cocoapods Release
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@main
    - name: Push Podspec To Cocopods
      env: 
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push --allow-warnings
